services:

  ghost:
    image: ghost:5-alpine
    restart: on-failure:5
    ports:
      - 8080:2368
    environment:
      database__client: mysql
      database__connection__host: db
      database__connection__user: root
      database__connection__password: F6keyX3Ok5mN
      database__connection__database: ghost
    volumes:
      - ghost:/var/lib/ghost/content
    networks:
      - ghost-network
      - ghost-mysql-network
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:8.0
    restart: on-failure:5
    environment:
      MYSQL_ROOT_PASSWORD: F6keyX3Ok5mN
      MYSQL_DATABASE: ghost
    volumes:
      - db:/var/lib/mysql
    networks:
      - ghost-mysql-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-uroot", "-pF6keyX3Ok5mN"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 30s

volumes:
  ghost:
    name: ghost-data
  db:
    name: ghost-mysql-data

networks:
  ghost-network:
    driver: bridge 
  ghost-mysql-network:
    driver: bridge
